"""Order repository port."""
from abc import ABC, abstractmethod
from core.domain.order import Order, OrderStatus


class IOrderRepository(ABC):

    @abstractmethod
    def save(self, order: Order) -> Order:
        """Insert a brand-new order. Order.id is generated by the caller
        (service layer) before this is called, so the repository never
        has to hand an ID back."""
        raise NotImplementedError

    @abstractmethod
    def get(self, order_id: str) -> Order | None:
        raise NotImplementedError

    @abstractmethod
    def update_status(self, order_id: str, new_status: OrderStatus) -> Order:
        """Persists a status that has ALREADY been validated by the domain
        layer (Order.transition_to). The repository does not re-validate
        the transition — that would duplicate business logic in the
        adapter, which is exactly what hexagonal architecture avoids."""
        raise NotImplementedError

    @abstractmethod
    def list_by_status(self, status: OrderStatus | None = None) -> list[Order]:
        """None returns all orders — used by the admin live dashboard."""
        raise NotImplementedError
